<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>Launcher</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <OptimizationPreference>Size</OptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <ApplicationIcon>..\Resources\vii\vii_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(DesignTimeBuild)' != 'true'">
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../LazyBootstrap/FileSystem/LauncherLocation.cs" Link="Shared/LauncherLocation.cs" />
    <Compile Include="../LazyBootstrap/FileSystem/SafeFileWriter.cs" Link="Shared/SafeFileWriter.cs" />
    <Compile Include="../LazyBootstrap/Serialization/AppConfigDocument.cs" Link="Shared/AppConfigDocument.cs" />
    <Compile Include="../LazyBootstrap/Serialization/AppConfigDefaults.cs" Link="Shared/AppConfigDefaults.cs" />
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>
</Project>
